/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  slug?: Slug;
  excerpt?: LocalizedText;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  publishedAt?: string;
  body?: LocalizedText;
};

export type LocalizedText = {
  _type: "localizedText";
  en?: string;
  ar?: string;
  tr?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type LocalizedString = {
  _type: "localizedString";
  en: string;
  ar?: string;
  tr?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  slug?: Slug;
  description?: LocalizedText;
};

export type LocalizedBlockContent = {
  _type: "localizedBlockContent";
  en?: BlockContent;
  ar?: BlockContent;
  tr?: BlockContent;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Post | LocalizedText | SanityImageCrop | SanityImageHotspot | Slug | LocalizedString | Category | LocalizedBlockContent | BlockContent | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: getAllPostsQuery
// Query: *[_type == "post"  && (    !defined($category) || $category == "" ||    $category in categories[]->slug.current  )  && (    !defined($searchPattern) || $searchPattern == "" ||    lower(coalesce(title[$locale], title[$defaultLocale], title.en, "")) match lower($searchPattern) ||    lower(coalesce(excerpt[$locale], excerpt[$defaultLocale], excerpt.en, "")) match lower($searchPattern) ||    lower(coalesce(body[$locale], body[$defaultLocale], body.en, "")) match lower($searchPattern) ||    count(categories[]->[lower(coalesce(title[$locale], title[$defaultLocale], title.en, "")) match lower($searchPattern)]) > 0  )]{  _id,  "title": coalesce(title[$locale], title[$defaultLocale], title.en),  "slug": slug.current,  "excerpt": coalesce(excerpt[$locale], excerpt[$defaultLocale], excerpt.en),  mainImage,  categories[]->{    _id,    "title": coalesce(title[$locale], title[$defaultLocale], title.en),    "slug": slug.current,  },  publishedAt,  "bodyText": coalesce(body[$locale], body[$defaultLocale], body.en, ""),} | order(publishedAt desc)
export type GetAllPostsQueryResult = Array<{
  _id: string;
  title: Array<{
    _type: "localizedString";
    en: string;
    ar?: string;
    tr?: string;
  }> | string | null;
  slug: string | null;
  excerpt: Array<{
    _type: "localizedText";
    en?: string;
    ar?: string;
    tr?: string;
  }> | string | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  categories: Array<{
    _id: string;
    title: Array<{
      _type: "localizedString";
      en: string;
      ar?: string;
      tr?: string;
    }> | string | null;
    slug: string | null;
  }> | null;
  publishedAt: string | null;
  bodyText: Array<{
    _type: "localizedText";
    en?: string;
    ar?: string;
    tr?: string;
  }> | string | "";
}>;
// Variable: getPostBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0]{  _id,  "title": coalesce(title[$locale], title[$defaultLocale], title.en),  "slug": slug.current,  "excerpt": coalesce(excerpt[$locale], excerpt[$defaultLocale], excerpt.en),  mainImage,  categories[]->{    _id,    "title": coalesce(title[$locale], title[$defaultLocale], title.en),    "slug": slug.current,  },  publishedAt,  "body": coalesce(body[$locale], body[$defaultLocale], body.en, ""),  "bodyText": coalesce(body[$locale], body[$defaultLocale], body.en, ""),}
export type GetPostBySlugQueryResult = {
  _id: string;
  title: Array<{
    _type: "localizedString";
    en: string;
    ar?: string;
    tr?: string;
  }> | string | null;
  slug: string | null;
  excerpt: Array<{
    _type: "localizedText";
    en?: string;
    ar?: string;
    tr?: string;
  }> | string | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  categories: Array<{
    _id: string;
    title: Array<{
      _type: "localizedString";
      en: string;
      ar?: string;
      tr?: string;
    }> | string | null;
    slug: string | null;
  }> | null;
  publishedAt: string | null;
  body: Array<{
    _type: "localizedText";
    en?: string;
    ar?: string;
    tr?: string;
  }> | string | "";
  bodyText: Array<{
    _type: "localizedText";
    en?: string;
    ar?: string;
    tr?: string;
  }> | string | "";
} | null;
// Variable: getBlogCategoriesQuery
// Query: *[_type == "category"] | order(coalesce(title[$locale], title[$defaultLocale], title.en) asc){  _id,  "title": coalesce(title[$locale], title[$defaultLocale], title.en),  "slug": slug.current,}
export type GetBlogCategoriesQueryResult = Array<{
  _id: string;
  title: Array<{
    _type: "localizedString";
    en: string;
    ar?: string;
    tr?: string;
  }> | string | null;
  slug: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"post\"\n  && (\n    !defined($category) || $category == \"\" ||\n    $category in categories[]->slug.current\n  )\n  && (\n    !defined($searchPattern) || $searchPattern == \"\" ||\n    lower(coalesce(title[$locale], title[$defaultLocale], title.en, \"\")) match lower($searchPattern) ||\n    lower(coalesce(excerpt[$locale], excerpt[$defaultLocale], excerpt.en, \"\")) match lower($searchPattern) ||\n    lower(coalesce(body[$locale], body[$defaultLocale], body.en, \"\")) match lower($searchPattern) ||\n    count(categories[]->[lower(coalesce(title[$locale], title[$defaultLocale], title.en, \"\")) match lower($searchPattern)]) > 0\n  )\n]{\n  _id,\n  \"title\": coalesce(title[$locale], title[$defaultLocale], title.en),\n  \"slug\": slug.current,\n  \"excerpt\": coalesce(excerpt[$locale], excerpt[$defaultLocale], excerpt.en),\n  mainImage,\n  categories[]->{\n    _id,\n    \"title\": coalesce(title[$locale], title[$defaultLocale], title.en),\n    \"slug\": slug.current,\n  },\n  publishedAt,\n  \"bodyText\": coalesce(body[$locale], body[$defaultLocale], body.en, \"\"),\n} | order(publishedAt desc)": GetAllPostsQueryResult;
    "\n*[_type == \"post\" && slug.current == $slug][0]{\n  _id,\n  \"title\": coalesce(title[$locale], title[$defaultLocale], title.en),\n  \"slug\": slug.current,\n  \"excerpt\": coalesce(excerpt[$locale], excerpt[$defaultLocale], excerpt.en),\n  mainImage,\n  categories[]->{\n    _id,\n    \"title\": coalesce(title[$locale], title[$defaultLocale], title.en),\n    \"slug\": slug.current,\n  },\n  publishedAt,\n  \"body\": coalesce(body[$locale], body[$defaultLocale], body.en, \"\"),\n  \"bodyText\": coalesce(body[$locale], body[$defaultLocale], body.en, \"\"),\n}": GetPostBySlugQueryResult;
    "*[_type == \"category\"] | order(coalesce(title[$locale], title[$defaultLocale], title.en) asc){\n  _id,\n  \"title\": coalesce(title[$locale], title[$defaultLocale], title.en),\n  \"slug\": slug.current,\n}": GetBlogCategoriesQueryResult;
  }
}
